### ISSUE TITLE
Trying to open the drawer goes back on Android Q with Gesture Navigation

### ISSUE THREAD

**Issue by cassidyjames** [tuskyapp/Tusky#1426]
This _might_ just get fixed automatically when fixing #1365, but I wanted to raise it here for visibility. On Android Q with Gesture Navigation enabled, swiping from the edges of the display performs the equivalent of a back button press. 

For apps with side navigation (like pull-out drawers), you can opt out of back gestures: https://developer.android.com/preview/features/gesturalnav

However, I believe the updated Android framework might do this automatically depending on how the drawer is implemented, so it's worth checking that.

**Comment by connyduck** [comment]
This will 100% get fixed by #1365

**Comment by jrtberlin** [comment]
@connyduck I think you forgot to actually add that or push the commit. This is still broken for me on the nightly and the stable release. I searched the commit history in #1537 for descriptions that match the issue but have not found something that looks like it implements [setSystemGestureExclusionRects](https://developer.android.com/reference/android/view/View#setSystemGestureExclusionRects(java.util.List%3Candroid.graphics.Rect%3E)).

Thanks for your work on Tusky!

**Comment by cassidyjames** [comment]
This might be because of a change Google made to the gestures in development of Android Q. I'm not 100% sure if apps can totally override the side gesture, or only exclude a certain-sized rectangle from the gestures.
