### ISSUE TITLE
Click a link in toots list (home screen) is confusing

### ISSUE THREAD

**Issue by Phyks** [tuskyapp/Tusky#375]
Hi,

When there are some links in toots on the home page (feed of toots), they are hilighted as regular links, which leads the user to think they can simply click them to open them in a browser.

I am not 100% sure I don't suffer from fat fingers problem, but I never managed to click a link in a toot from a toot list to open it in the browser. Instead, it always send me to the "this toot's thread view", where I can click the link.

It's a bit confusing and adds extra clicks to actually browse the link, would be awesome if we could click on links in toots directly from the homepage! :)

Thanks!

**Comment by Vavassor** [comment]
You are _supposed_ to be able to click the links in the timeline, but it's true, the detection area is very tiny. Tags have the same issue.

In general, android doesn't have provisions to let you control touch priority or, like, let you expand how big you can touch things separately from how big they're drawn and how much space the layout system gives them. You can manually handle the touch detection, but the time I experimented with it, it ended up more janky than without my changes.

It definitely needs to be given another go. Or some other approach needs to be thought of :/

**Comment by Phyks** [comment]
Thanks for the explanations! An idea might be to put a right arrow at the right of toots in timeline and only display the full toot on click on this arrow?

**Comment by jeroenpraat** [comment]
Works for me most of the times. So please make it configurable if this is changed.

**Comment by Phyks** [comment]
Maybe it's a bug in Tusky and some Android versions? I am using latest version from FDroid, Android 4.2.2 and a Fairphone FP1, in case it might be useful. 

No matter how hard I try to click precisely on the link, it never works for me :/

Additionally, once I open a link from Tusky (in Firefox for Android) in a single thread view, go back to Tusky and click "back" button in the top left corner of the screen to go back to timeline view, it sends me back to Firefox app instead of opening timeline view in Tusky. I can then switch back to Tusky and click back again and it works this time. 
-- 
Phyks

**Comment by different55** [comment]
Could it be helped by increasing font size or line spacing?

**Comment by charlag** [comment]
I'm not sure what we can do here, we can let users configure font size (it is a requested feature anyway) but handling link... I don't know, I haven't had any problems ever and I don't even make effort. It's probably something device/OS version specific.

**Comment by connyduck** [comment]
Tusky 1.4 has an option to change font size and bigger line spacing, I think this should be resolved

**Comment by Phyks** [comment]
I tried it, but sadly it does not fix the issue in my case (Android 4.2.2). I still can't click links directly from a toot feed, I have to be in the thread view. Clicking on a link from a toot feed just opens the thread.

> Additionally, once I open a link from Tusky (in Firefox for Android) in a single thread view, go back to Tusky and click "back" button in the top left corner of the screen to go back to timeline view, it sends me back to Firefox app instead of opening timeline view in Tusky. I can then switch back to Tusky and click back again and it works this time.

Additionnally, I tried checking the "use internal browser" option, but this behavior is still present and opens links in Firefox in this case.

**Comment by charlag** [comment]
We don't support Android 4 anymore, feel free to reopen if it happens with supported Android.
