### ISSUE TITLE
Don't recollapse filter after every interaction

### ISSUE THREAD

**Issue by nehemiagurl** [tuskyapp/Tusky#4125]
Filtered post recollapse to their filtered form after every interaction (like, boost, bookmark). This makes for a clunky experience and is genuinely just annoying as the recollapse feels unprompted.

In the vid below it happens in a hashtag feed, but it also happens in home and local, but *doesn't* happen in thread view. 

https://github.com/tuskyapp/Tusky/assets/109424320/2c82638c-d469-4c01-b35d-311ffde95751
* * * *
- Tusky Version: 24 beta 1
- Android Version: 12
- Android Device: Galaxy A12

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Thanks for reporting @nehemiagurl!

I think this could easily be fixed by not upding the filter column in `TimelineDao.update`. But it needs careful investigation as it might have unintended sideeffects 🤔

**Comment by Sirs0ri** [comment]
I'm still seeing this issue on the local and federated timeline, while it has been fixed and works as intended (no collapsing after and interaction) on the home timeline.

It happens for both, liking and bookmarking a toot that's been hidden through a filter, and in both cases, the filter was re-applied and the post hidden as shown in the video of the original issue.

Tusky Test 24.1 beta 1-d2cb74b6
Android 12, on an Galaxy S10e
